### ISSUE TITLE
Could use some build instructions

### ISSUE THREAD

**Issue by anzzstuff** [makotot/react-scrollspy#25]
I've got some ideas I'd like to contribute, but I can't figure out how to set up the project to run on its own. Tried with the typical `npm install` and `npm start` but ran into some problems (gulp was missing, installed it as global, got more errors)

**Comment by makotot** [comment]
Can you show me the error message?

**Comment by anzzstuff** [comment]
```
[18:16:19] Using gulpfile ~\Code\react-scrollspy\gulpfile.js
[18:16:19] Starting 'serve'...
[18:16:19] Starting 'clean'...
[18:16:19] Finished 'serve' after 50 ms
[18:16:19] Finished 'clean' after 53 ms
[18:16:19] Starting 'lint'...
[18:16:19] Finished 'lint' after 136 ms
[18:16:19] Starting 'template'...
[18:16:19] Starting 'script'...
[18:16:19] Starting 'css'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
 ESLintError: Trailing spaces not allowed.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react-scrollspy@2.1.2 serve: `gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-scrollspy@2.1.2 serve script 'gulp serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-scrollspy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-scrollspy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-scrollspy
npm ERR! There is likely additional logging output above.
```

**Comment by makotot** [comment]
Thanks :)
The error message with `ESLintError` is not about the project settings, it is an error about eslint.
http://eslint.org/docs/rules/no-trailing-spaces
Probably you left a trailing space at the end of lines in a javascript file, so please check the javascript files you edited.

**Comment by anzzstuff** [comment]
I'm getting an error with a clean clone of this repo as well, though.
```
[18:41:52] Using gulpfile ~\Code\scrollspy2\gulpfile.js
[18:41:52] Starting 'serve'...
[18:41:52] Starting 'clean'...
[18:41:52] Finished 'serve' after 29 ms
[18:41:52] Finished 'clean' after 31 ms
[18:41:52] Starting 'lint'...
[18:41:52] Finished 'lint' after 28 ms
[18:41:52] Starting 'template'...
[18:41:52] Starting 'script'...
[18:41:52] Starting 'css'...
[18:41:53]
src\js\app.jsx
   3:10  warning  "Scrollspy" is defined but never used     no-unused-vars
   5:7   warning  "App" is defined but never used           no-unused-vars
  18:12  warning  Gratuitous parentheses around expression  no-extra-parens

src\js\lib\Scrollspy.jsx
   79:12  warning  Gratuitous parentheses around expression  no-extra-parens
   79:38  warning  Gratuitous parentheses around expression  no-extra-parens
  130:12  warning  Gratuitous parentheses around expression  no-extra-parens

✖ 6 problems (0 errors, 6 warnings)

[18:41:53] Finished 'css' after 988 ms
[18:41:53] Finished 'template' after 1.01 s
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'react' from 'C:\Users\anzz\Code\scrollspy2\src\js'
    at C:\Users\anzz\Code\scrollspy2\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\anzz\Code\scrollspy2\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\anzz\Code\scrollspy2\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\anzz\Code\scrollspy2\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\anzz\Code\scrollspy2\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\anzz\Code\scrollspy2\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

and after `npm install react`

```
[18:42:51] Using gulpfile ~\Code\scrollspy2\gulpfile.js
[18:42:51] Starting 'serve'...
[18:42:51] Starting 'clean'...
[18:42:51] Finished 'serve' after 30 ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EPERM
    at exports._errnoException (util.js:1008:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
```

**Comment by makotot** [comment]
Hmmm, i don't use Windows, but it seems to an permission issue with Windows.

**Comment by anzzstuff** [comment]
Yeah I don't know, it feels like the error is coming and going randomly. I guess the problem is on my end, I haven't used ESLint before so I'll try to figure it out.
